### ISSUE TITLE
@conda-forge-admin, please add user @conda-forge/sphinx

### ISSUE THREAD

**Issue by AA-Turner** [conda-forge/sphinx-autosummary-accessors-feedstock#7]

**Comment by keewis** [comment]
while I'm always open to additional maintainers, this does feel a bit sudden. @AA-Turner, could you elaborate, please?

**Comment by AA-Turner** [comment]
I saw this done with ``R`` related packages on conda-forge, and it seemed like a reasonable idea to cross-pollinate by having a central team (``sphinx``) be able to help with the various Sphinx-affiliated packages on CF. No objections to just having this PR closed, though.

Thanks,
Adam

**Comment by keewis** [comment]
that makes sense, thanks for explaining (and thanks in advance for putting in the time to help)
